version: '2'
services:
    jhipster190120-app:
        image: jhipster190120
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipster190120-mysql:3306/jhipster190120?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jhipster190120-mysql:
        extends:
            file: mysql.yml
            service: jhipster190120-mysql
